language: rust
dist: bionic

cache: cargo
rust:
  - stable

addons:
    apt:
        packages:
            - libssl-dev

before_script: |
  cargo install cargo-tarpaulin

script:
  - cargo build --release
  - cargo build --release --features parallelism
  - cargo test
  - cargo test system_checks --features "parallelism no-core-check" -- --nocapture
  - cargo test --features "parallelism no-core-check"

after_success: |
  cargo tarpaulin --features "parallelism no-core-check" --out Xml
  bash <(curl -s https://codecov.io/bash)