language: rust
dist: bionic

cache: cargo
rust:
  - stable

addons:
    apt:
        packages:
            - libssl-dev

before_script: |
  cargo install cargo-tarpaulin

script:
  - cargo build --release
  - cargo build --release --features parallelism
  - cargo test
  - cargo test --features parallelism

after_success: |
  cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash)