language: rust

rust:
  - stable

addons:
  apt:
    packages:
      - kcov

script:
  - cargo build --release
  - cargo test --lib

after_success: |
  kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/deps/tin-* &&
  bash <(curl -s https://codecov.io/bash)